alias gc="git commit"
alias gs="git status"
alias gp="git push"
alias ga="git add"
alias gpp="git pull"
alias gr="git rebase -i"
alias rebaseMaster="gco master && gpp && gco - && gr master"
alias fpush="git push -f origin"
